package main

var (
	data = []string{
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
		"2 Double",
		"1 Double or Twin",
		"1 Double / 2 Twin",
		"1 Double",
		"2 Twin",
		"1 Twin",
		"1 Queen / 2 Single",
		"3 Bunk Bed",
		"Double bed",
		"2 Single",
		"1 King",
		"2 Single / 2 Bunk Bed",
		"1 Double bed 131-150 width",
		"1 Queen-size bed 150-154 width",
		"2 Double bed 131-150 width",
		"1 double bed",
		"2 single beds and 1 queen bed and 1 king bed",
		"1 king bed and 1 queen bed",
		"1 double bed or 2 single beds",
		"1 Extra Large Double",
		"1 Single & 1 Double",
		"3 Single & 1 Double",
		"1 Single & 1 Double & 1 Extra Large Double",
		"1 Double & 1 Twin",
		"2 Single / 1 Double",
		"1 Double / 2 Single",
		"1 Double / 1 Twin",
		"2 Single bed 80-130 width",
		"1 double bed and 2 single beds",
		"1 Bunk Bed",
		"1 king bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 1 king bed",
		"1 King-size bed 150-183 width",
		"Double",
		"1 Twin / 1 King",
		"2 King",
		"1 Single & 2 Double",
		"Single bed",
		"2 single beds",
		"1 single bed",
		"4 King",
		"Twin bed",
		"1 Single",
		"1 King & 1 Bunk Bed",
		"2 Queen",
		"2 Other",
		"1 Double & 2 Twin",
		"2 Bunk Bed",
		"1 Twin / 2 Twin",
		"Large bed (King size)",
		"3 King",
		"2 Double & 1 Twin",
		"1 Single & 2 King",
		"2 single beds and 1 king bed",
		"1 queen bed and 1 single bed",
		"1 double bed and 1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Common space :1 king bed",
		"2 king beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed or 2 single beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed;Bedroom 3: :1 king bed or 2 single beds",
		"3 king beds",
		"5 king beds or 2 bunk beds",
		"2 single beds and 2 double beds",
		"1 king bed and 1 double bed",
		"2 double beds",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 single bed",
		"Bedroom 1: :1 king bed;Bedroom 2: :1 king bed",
		"2 Single & 1 Double",
		"1 Single & 1 Queen",
		"2 Single / 1 Sofabed",
		"2 Single & 1 King",
		"2 single beds or 1 double bed",
		"2 queen beds",
		"1 king bed or 2 single beds",
		"Bunk bed",
		"3 Single",
		"1 Single & 1 King",
		"1 Queen",
	}
)
